server:
  port: 9000

#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/craftbeer
#    username: 'root'
#    password: 'root'
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver